services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    container_name: test-runner
    env_file:
      - .env
    networks:
      - test-net
    volumes:
      - .:/app
    command: >
      sh -c "
      echo 'Waiting for Supabase DB connection...';
      /usr/local/bin/wait-for-it $DB_HOST:$DB_PORT --timeout=30 --;
      gotestsum --format standard-verbose ./internal/... -cover -v
      "
networks:
  test-net:
    driver: bridge
