name: Run Tests

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Generate go.sum file
        run: go mod tidy

      - name: Run Tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SSLMODE: disable
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner
      

      - name: Wait for Supabase Test DB
        run: |
            echo "Waiting for Supabase test database..."
            for i in {1..10}; do
              nc -zv ${{ secrets.DB_HOST }} 5432 && echo "Database is ready!" && exit 0
              echo "Database is not ready yet... retrying in 5s"
              sleep 5
            done
            echo "Database failed to start in time."
            exit 1
            
      - name: Run Tests
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner
